### ISSUE TITLE
logstash 8.1.5    logstash-input-snmptrap IPV6 

### ISSUE THREAD

**Issue by 13593168165** [logstash-plugins/logstash-integration-snmp#69] opened 2024-08-15 11:40 UTC
[INFO ][logstash.inputs.snmptrap ] It's a Trap! {:Port=>10620, :Community=>["public"], :Host=>"fd00:192:168:67::41"}
[2024-01-18T10:26:27,807][WARN ][logstash.inputs.snmptrap ] SNMP Trap listener died {:exception=>#<socketError:bin: unsupported address "fd00:192:168:67::41" for protocol family inet>

**Comment by edmocosta** [comment] 2024-08-16 09:13
Hi there! This log seems to be generated by the individual SNMP traps plugin (https://github.com/logstash-plugins/logstash-input-snmptrap), and not by this integration one. 

The individual traps plugin does not support IPv6, which is the probably causing this error.  
If you want to migrate to the new integration plugin, please have a look at the  [behaviour changes](https://www.elastic.co/guide/en/logstash/current/plugins-integrations-snmp.html#plugins-integrations-snmp-migration), and run the following command:

```
bin/logstash-plugin install logstash-integration-snmp       
```

It will automatically replace both individual SNMP plugins (`snmp`, `snmptrap`) by this integration one, and it should support IPV6.

**Comment by edmocosta** [comment] 2024-08-22 09:11
Closing this issue for now, please feel free to re-open it if the problem is happening with this integration plugin. Thanks!

**Closed by edmocosta** 2024-08-22 09:11 UTC
Labels: bug
